config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about' => 'welcome#show', as: 'about'
  devise_for :patients
  devise_for :doctors
  post 'medication_search' => 'prescriptions#medication_search'

  resources :doctors, only: [:show] do
    resources :prescriptions, only: [:new, :create, :destroy]
    get 'patients/drop', as: "patients_drop"
    patch 'patient/compliance' => 'doctors#compliance', as: 'patient_compliance'
    resources :patients, only: [:index, :show, :new, :create, :destroy]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :patients, only: [:show] do
    resources :scheduled_doses, only: [:index]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :scheduled_doses, only: [:update]

  resources :prescriptions, only: [:show]

 

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  def authenticate_user!
    return if doctor_signed_in?
    return if patient_signed_in?
  end

  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]

  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found.'
    redirect_back_or root_path
  end
   
  def redirect_back_or(path)
    redirect_to request.referer || path
  end

  def show
    umn = user_model_name
    user = send("current_#{umn}")
    get_conversation.mark_as_read(user)
  end
 
  def index
    @conversations = (@mailbox.inbox | @mailbox.sentbox).sort_by{ |convo| convo.updated_at }.reverse
  end

  def reply
    umn = user_model_name
    send("current_#{umn}").reply_to_conversation(@conversation, params[:body])
    redir_url = send("#{umn}_conversation_path", send("current_#{umn}"), @conversation)
    flash[:success] = 'Reply sent'
    redirect_to redir_url
  end
 
  private
 
  def get_conversation
    @conversation = @mailbox.conversations.find(params[:id])
  end
 
  def get_mailbox
    umn = user_model_name
    @mailbox = send("current_#{umn}").mailbox
  end

  def user_model_name
    if doctor_signed_in?
      "doctor"
    elsif patient_signed_in?
      "patient"
    end
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <% if doctor_signed_in? %>
    <%= link_to conversation.subject, doctor_conversation_path(current_doctor, conversation) %>
  <% elsif patient_signed_in? %>
    <%= link_to conversation.subject, patient_conversation_path(current_patient, conversation) %>
  <% end %>
</li>

app/views/conversations/index.html.erb
<h3>Your Conversations</h3>

<% if doctor_signed_in? %>
  <p><%= link_to 'Start conversation', new_doctor_message_path(current_doctor), class: 'btn btn-lg btn-primary' %></p>
<% elsif patient_signed_in? %>
  <p><%= link_to 'Start conversation', new_patient_message_path(current_patient), class: 'btn btn-lg btn-primary' %></p>
<% end %>

<ul class="list-group">
  <%= render partial: 'conversations/conversation', collection: @conversations %>
</ul>

app/views/conversations/show.html.erb
<h3>Conversation</h3>
 
<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>
 
  <div class="panel-body">
    <div class="messages">
    <% if doctor_signed_in? %>
      <% @conversation.receipts_for(current_doctor).each do |receipt| %>
        <% message = receipt.message %>
 
        <%= message.sender.name %>
          says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %><br>
        &nbsp;&nbsp;&nbsp;&nbsp; <%= message.body %>
        <br><br>
      <% end %>
      <br>
      <%= form_tag reply_doctor_conversation_path(current_doctor, @conversation), method: :post do %>
        <div class="form-group">
          <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
        </div>
        <%= submit_tag "Send Message", class: 'btn btn-primary' %>
      <% end %>
    <% elsif patient_signed_in? %>
      <% @conversation.receipts_for(current_patient).each do |receipt| %>
        <% message = receipt.message %>
 
        <%= message.sender.name %>
          says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %><br>
        &nbsp;&nbsp;&nbsp;&nbsp; <%= message.body %>
        <br><br>
      <% end %>
      <br>
      <%= form_tag reply_patient_conversation_path(current_patient, @conversation), method: :post do %>
        <div class="form-group">
          <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
        </div>
        <%= submit_tag "Reply", class: 'btn btn-primary' %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>