config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about' => 'welcome#show', as: 'about'
  devise_for :patients
  devise_for :doctors
  post 'medication_search' => 'prescriptions#medication_search'

  resources :doctors, only: [:show] do
    resources :prescriptions, only: [:new, :create, :destroy]
    get 'patients/drop', as: "patients_drop"
    patch 'patient/compliance' => 'doctors#compliance', as: 'patient_compliance'
    resources :patients, only: [:index, :show, :new, :create, :destroy]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :patients, only: [:show] do
    resources :scheduled_doses, only: [:index]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :scheduled_doses, only: [:update]

  resources :prescriptions, only: [:show]

 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

   def index
   end 

   def show
   end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h2>Welcome to MedMed</h2>

<% if !current_doctor && !current_patient %>

    <div class="row">
      <div class="col-lg-6">
        <div class="well">
          <H3>DOCTOR LOGIN</H3>
          <%= link_to("Doctor, Please click to login.", new_doctor_session_path) %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="well">
          <H3>PATIENT LOGIN</H3>
          <%= link_to("Patient, please click to login.", new_patient_session_path) %>
        </div>
      </div>
    </div>

<% end %>

  <div class="jumbotron">
    <div class="row">
      <div class="col-md-7">
        <h1>MedMed</h1>
        <p class="lead">Helping doctors and patients manage complicated prescription regimens.</p>
        <p><%= link_to('Learn more', about_path, class: "btn btn-primary btn-lg")%></a></p>
      </div>
      <div class="col-md-5"> <%= image_tag("medmed", class: "img-responsive img-right") %> </div>
    </div>


  </div>

app/views/welcome/show.html.erb
<!DOCTYPE html>
<html lang="en">


<body>

    <!-- Page Content -->
    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">About Us
                    <small>We're Team MedMed!</small>
                </h1>
                <p class="lead">MedMed is an awesome application that allows doctors and patients to manage complicated prescription regimens. A doctor can add a patient, assign them a prescription, and monitor their patient's compliance. A patient can see what scheduled medication they have to take, report any side effects they might have, and receive text reminders.</p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">The Team</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-xs-12 text-center">
                <%= image_tag("ben", class: "img-circle img-responsive img-center") %>
                <h3>Ben Brattain<br/>
                    <small>Coding Boo</small>
                </h3>
                <p>I'm super sneaky. As soon as you've looked away I've built something else!</p>
                <a href="https://github.com/benbrattain"><%= fa_icon "github 3x" %></a>
            </div>

            <div class="col-lg-6 col-sm-6 col-xs-12 text-center">
                <%= image_tag("liz", class: "img-circle img-responsive img-center") %>
                <h3>Elizabeth Lovero<br/>
                    <small>Bob-omb Engineer</small>
                </h3>
                <p>My code compiles like explosions in the sky.</p>
                <a href="https://github.com/lizlove"><%= fa_icon "github 3x" %></a>
            </div>       
        </div>
        <br/><br/>
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-xs-12 text-center">
                <%= image_tag("lia", class: "img-circle img-responsive img-center") %>
                <h3>Lia Skalkos<br/>
                    <small>Shy Guy Developer</small>
                </h3>
                <p>I'm really humble about how good of a developer I am.</p>
                <a href="https://github.com/lskalkos"><%= fa_icon "github 3x" %></a>
            </div>
        
            <div class="col-lg-6 col-sm-6 col-xs-12 text-center">
               <%= image_tag("joe", class: "img-circle img-responsive img-center") %>
                <h3>Joe Sutker<br/>
                    <small>Koopagrammer</small>
                </h3>
                <p>I love programming in my awesome shell!</p>
                <a href="https://github.com/jsutker"><%= fa_icon "github 3x" %></a>
            </div>
        </div>

        <hr>


    </div>
    <!-- /.container -->

    <!-- jQuery -->

</body>

</html>