config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about' => 'welcome#show', as: 'about'
  devise_for :patients
  devise_for :doctors
  post 'medication_search' => 'prescriptions#medication_search'

  resources :doctors, only: [:show] do
    resources :prescriptions, only: [:new, :create, :destroy]
    get 'patients/drop', as: "patients_drop"
    patch 'patient/compliance' => 'doctors#compliance', as: 'patient_compliance'
    resources :patients, only: [:index, :show, :new, :create, :destroy]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :patients, only: [:show] do
    resources :scheduled_doses, only: [:index]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :scheduled_doses, only: [:update]

  resources :prescriptions, only: [:show]

 

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  acts_as_messageable
  include Userify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, :phone_number, :email, presence: true
  validate :phone_number_is_valid_mobile

  has_many :doctor_patients
  has_many :doctors, through: :doctor_patients
  has_many :prescriptions
  has_many :scheduled_doses, through: :prescriptions

  def translated_time_zone
    ActiveSupport::TimeZone.new(self.time_zone)
  end

  def scheduled_doses_for_today
    scheduled_doses_by_time.where({scheduled_time: Time.now.midnight..(Time.now.midnight + 1.day)})
  end

  def missed_doses_for_yesterday
    scheduled_doses_by_time.where({scheduled_time: (Time.now.midnight-1.day)..(Time.now.midnight), was_taken: false})
  end

  def missed_scheduled_dose?
    self.missed_doses_for_yesterday.any?
  end

   def get_side_effects_last_7_days
    self.scheduled_doses.select { |m| !!m.taken_time && !!m.side_effect && (m.taken_time > (Time.now - 7.days))}
  end

  private
  def phone_number_is_valid_mobile
    if !(SmsWrapper.new(self).valid_phone_number?)
      errors.add(:phone_number, "is not a valid cell phone number")
    end
  end

  def scheduled_doses_by_time
    self.scheduled_doses.order(:scheduled_time)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update]

  def index
    @doctor = current_doctor
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.find(params[:patient][:id])
    @doctor = current_doctor
    @doctor.patients << @patient
    redirect_to doctor_patients_path
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if (params[:id] != "0") && (params[:id] != "")
      @patient = Patient.find(params[:id])
      current_doctor.patients.destroy(@patient)
      redirect_to doctor_patients_path
    else
      redirect_to doctor_patients_drop_path
    end
  end

  def drop
    @patient = Patient.new
    @doctor = current_doctor
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :time_zone)
  end
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/patients/_charts.html.erb
<div class="row">
  <!-- panel barchart -->
  <div class="col-lg-6" id="bardiv">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5>Percent Compliance</h5>
      </div>
      <div id="barlabel" style="display: none">
        <% @comply = DoctorComplianceData.new(@doctor) %>
        <% if @patient %>
          <%= @patient.prescriptions.collect{|prescription| prescription.medication_name}.join(", ") %>
        <% else %>
          <%= @comply.patients_labelmaker.join(", ")%>
        <% end %>
      </div>
      <div id="bardata" style="display:none">
        <% if @patient %>
          <%= @patient.prescriptions.collect{|prescription| @comply.single_prescription_compliance_percentage_calculator(prescription)}.join(", ") %>
        <% else %>
          <%= @comply.all_doctor_patients_compliance_array.join(", ") %>
        <% end %>
      </div>
      <canvas id="barchart" width="400" height="200"></canvas>
    </div>
  </div>
  <!-- /panel barchart -->

  <!-- /panel donut -->
  <div class="col-lg-6" id="donutdiv">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5>Total Compliance: <%= @taken = @comply.total_doctor_patients_compliance_figure %>% taken within 4 hours of scheduled dose</h5>
      </div>
        <div class="panel-body text-center">       
          <!--Start Donut Chart-->
          <!--===================================================-->
          <div id="taken" style="display: none">
            <%= @taken %>
          </div>
          <div id="missed" style="display:none">
            <%= 100 - @taken %>
          </div>
          <div id="totaldonut" class="pie-title-center">
            <canvas id="donut" width="400" height="200"></canvas>
          </div>
          <!--===================================================-->
          <!-- End Donut Chart -->
        </div>
    </div>
  </div>
  <!-- /panel donut -->
  </div>

app/views/patients/_form.html.erb
<%= form_for(@patient,url: doctor_patients_path) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient %><br>
    <%= f.collection_select :id, Patient.all-current_doctor.patients, :id, :name, {}, {class: 'form-control'} %><br>
  </div>

  <div class="actions">
    <%= f.submit "Add Patient", type: 'submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/patients/drop.html.erb
<h1>Drop one of your patients</h1>

<%= form_for(@patient, url: doctor_patient_path(id: 0), html: {id: "delete_patient", method: :delete}, :data => {:doctor_id => @doctor.id}) do |f| %>

  <div class="field">
    <%= f.label :patient %><br>
    <%= f.collection_select :id, @doctor.patients, :id, :name, {include_blank: "Select a patient"}, {class: 'form-control'} %><br>
  </div>

  <div class="actions">
    <%= f.button "Drop Patient", type: 'submit', class: 'btn btn-primary' %>
  </div>
<% end %>



<%= link_to 'Back', doctor_patients_path %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= link_to 'Back', :back %>

<%= render 'form' %>

app/views/patients/index.html.erb
<% if @doctor %>
<h1>Hello Dr. <%= @doctor.last_name %> <i class="fa fa-user-md fa-2x"></i></h1>
<br><br>
  <!-- panel row -->
  <div class="row">
    <div class="col-lg-3 col-md-6">
      <a href="<%= doctor_conversations_path(@doctor) %>">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="fa fa-comments fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
              <h1><%= @doctor.mailbox.inbox(unread: true).count %></h1>
              <div>New Messages!</div>
            </div>
          </div>
        </div>
          <div class="panel-footer">
            <span class="pull-left">View Messages</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
      </div>
      </a>
    </div>
    <div class="col-lg-3 col-md-6">
      <a href="<%= new_doctor_prescription_path %>">
          <div class="panel panel-success">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-tasks fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <h1><%= @doctor.prescriptions.count %></h1>
                  <div>Prescriptions</div>
                </div>
              </div>
            </div>
              <div class="panel-footer">
                <span class="pull-left">Prescribe a medication</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
          </div>
      </a>
    </div>
    <div class="col-lg-3 col-md-6">
      <a href="<%= new_doctor_patient_path %>">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="fa fa-user-plus fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
              <h1><%= @doctor.patients.count %></h1>
              <div>Add Patient</div>
            </div>
          </div>
        </div>

          <div class="panel-footer">
            <span class="pull-left">Add a patient</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
          </div>
      </div>
      </a>
    </div>
    <div class="col-lg-3 col-md-6">
        <a href="<%= doctor_patients_drop_path %>">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-exclamation-circle fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <h1>-</h1>
                  <div>Drop Patient</div>
                </div>
              </div>
            </div>
              <div class="panel-footer">
                <span class="pull-left">Drop a patient</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
          </div>
        </a>
    </div>
  </div>
  <!-- panel row -->
<br><br>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Active Precriptions</h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Patient Name</th>
          <th>Prescription</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Compliance</th>
          <th>Delete?</th>
        </tr>
      </thead>
      <tbody>
        <% @doctor.patients.order(:last_name).each do |patient| %>
          <% (@doctor.prescriptions & patient.prescriptions).each do |prescription| %>
            <tr>
              <td><%= link_to patient.name, doctor_patient_path(@doctor, patient), class: "btn btn-default disabled btn-sm" %></td>
              <td><%= link_to("#{prescription.medication_name}", prescription_path(prescription))%></td>
              <td><%= prescription.start_datetime.to_date %></td>
              <td><%= prescription.end_datetime.to_date %></td>
              <td><%= prescription.scheduled_doses.where(was_taken: true).length %>/<%= prescription.scheduled_doses.where(scheduled_time: (100.years.ago)..(Time.now)).length %></td>
              <td><%= link_to('Delete', doctor_prescription_path(id: prescription.id), method: "DELETE", class: "btn btn-danger btn-xs", data: {confirm: "Are you sure?"}) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>



  <div class="row">
  <!-- panel barchart -->
  <div class="col-lg-6" id="bardiv">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5>Percent Compliance</h5>
      </div>
      <div id="barlabel" style="display: none">
        <% @comply = DoctorComplianceData.new(@doctor) %>
        <%= @comply.patients_labelmaker.join(", ")%>
      </div>
      <div id="bardata" style="display:none">
        <%= @comply.all_doctor_patients_compliance_array.join(", ") %>
      </div>
      <canvas id="barchart" width="400" height="200"></canvas>
    </div>
  </div>
  <!-- /panel barchart -->

  <!-- /panel donut -->
  <div class="col-lg-6" id="donutdiv">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5>Total Compliance: <%= @taken = @comply.total_doctor_patients_compliance_figure %>% taken within 4 hours of scheduled dose</h5>
      </div>
        <div class="panel-body text-center">       
          <!--Start Donut Chart-->
          <!--===================================================-->
          <div id="taken" style="display: none">
            <%= @taken %>
          </div>
          <div id="missed" style="display:none">
            <%= 100 - @taken %>
          </div>
          <div id="totaldonut" class="pie-title-center">
            <canvas id="donut" width="400" height="200"></canvas>
          </div>
          <!--===================================================-->
          <!-- End Donut Chart -->
        </div>
    </div>
  </div>
  <!-- /panel donut -->
  </div>

  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Side Effects</h1>
    </div>
  <div class="col-lg-12">
  <!--Danger Panel-->
  <!--===================================================-->
    <div class="panel panel-bordered panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Reported Side Effects in the Last 7 Days</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Medication</th>
                <th class="text-center">Effect Reported</th>
                <th class="text-center">Date Reported</th>
                <th class="text-right">Contact Patient</th>
              </tr>
            </thead>
            <tbody>
              <% @doctor.patients.each do |patient| %>
                <% patient.get_side_effects_last_7_days.each do |dose| %>
                  <tr>
                    <td class="text-center"><%= patient.name %></td>
                    <td class="text-center"><%= dose.medication_name %></td>
                    <td class="text-center"><%= dose.side_effect %></td>
                    <td class="text-center"><%= dose.taken_time %></td>
                    <td class="text-right">
                      <a class="btn btn-xs btn-default add-tooltip" data-toggle="tooltip" href="<%= new_doctor_message_path(@doctor)%>" data-original-title="Edit" data-container="body"><i class="fa fa-pencil"></i></a>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!--===================================================-->
  <!--End Danger Panel-->
  </div>

</div>
<% else %>
<h4>You're not signed in!</h4>
<% end %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', doctor_patients_path %>

app/views/patients/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h3 id="container">Contact Information</h3>
    </div>
    <div class="contact-info">
      <p>
      <h3>Name:</h3>
      <%= @patient.name %>
      </p>

      <p>
      <h3>Email:</h3>
      <%= @patient.email %>
      </p>

      <p>
      <h3>Phone Number:</h3>
      <%= @patient.phone_number %>
      </p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h3 id="container">Doctors</h3>
    </div>
    <div class="doctor-info">
      <div class="list-group">
        <% @patient.doctors.each do |doctor| %>
            <h4 class="list-group-item-heading">Dr. <%= doctor.name %></h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h3 id="container">Prescriptions</h3>
    </div>
  </div>

  <div class="prescription-info">
    <table class="table table-striped table-hover ">
      <thead>
      <tr>
        <th>Prescription</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Prescribing Doctor</th>
        <th>Compliance</th>
      </tr>
      </thead>
      <tbody>
      <% @patient.prescriptions.each do |prescription| %>
          <tr>
            <td><%= prescription.medication_name %></td>
            <td><%= prescription.start_datetime.to_date %></td>
            <td><%= prescription.end_datetime.to_date %></td>
            <td><%= prescription.doctor.name %></td>
            <td><%= prescription.scheduled_doses.where(was_taken: true).length %>/<%= prescription.scheduled_doses.where(scheduled_time: (100.years.ago)..(Time.now)).length %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>