config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/about' => 'welcome#show', as: 'about'
  devise_for :patients
  devise_for :doctors
  post 'medication_search' => 'prescriptions#medication_search'

  resources :doctors, only: [:show] do
    resources :prescriptions, only: [:new, :create, :destroy]
    get 'patients/drop', as: "patients_drop"
    patch 'patient/compliance' => 'doctors#compliance', as: 'patient_compliance'
    resources :patients, only: [:index, :show, :new, :create, :destroy]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :patients, only: [:show] do
    resources :scheduled_doses, only: [:index]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
      end
    end
    resources :messages, only: [:new, :create]
  end

  resources :scheduled_doses, only: [:update]

  resources :prescriptions, only: [:show]

 

end

app/controllers/scheduled_doses_controller.rb
class ScheduledDosesController < ApplicationController
  before_action :set_dose, only: [:update]

  def index
    @patient = Patient.find(params[:patient_id])
  end 

  def update
    @patient = Prescription.find(dose_params[:prescription_id]).patient
    @scheduled_dose.taken_time = Time.now
    respond_to do |format|
      if @scheduled_dose.update(dose_params)
        format.html { redirect_to patient_scheduled_doses_path(@patient) }
        format.js
      end
    end
  end

  private

  def set_dose
    @scheduled_dose = ScheduledDose.find(params[:id])
  end

  def dose_params
    params.require(:scheduled_dose).permit(:prescription_id, :scheduled_time, :taken_time, :side_effect, :was_taken)
  end
end

app/helpers/scheduled_doses_helper.rb
module ScheduledDosesHelper
end

app/views/scheduled_doses/_scheduled_dose.html.erb
<% sd_view = ScheduledDoseView.new(sd) %>
<div class="panel panel-<%= sd_view.panel_class %>" data-id="<%= sd.id %>">
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-6">
        <%= link_to("#{sd.medication_name}", prescription_path(sd.prescription), class: "script_link")%>
      </div>
      <div class="col-lg-6">
        <div class="checkbox">
          <label for="">
            <%= form_for(sd, remote: true) do |f| %>
                <%= f.hidden_field :prescription_id, value: sd.prescription_id %>
                <%= f.check_box :was_taken %>
            <% end %>
            Taken
          </label>

        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-6">
        <img src=<%= sd.prescription.get_image %> alt="pill_image">
        <%= sd_view.formatted_time %>
      </div>
      <div class="col-lg-6">
        <%= form_for(sd, remote: true) do |f| %>
            <%= f.hidden_field :prescription_id, value: sd.prescription.id %>
            <%= f.text_area :side_effect, class: "form-control", rows: "3", :disabled => !sd.was_taken? %>
            <br/>
            <%= f.submit "Record Side Effects", class: "btn btn-default", :disabled => !sd.was_taken? %>
            <div class="side_effect_notice">
              <h5 class="text-success">
                <%= sd_view.side_effect_text %>
              </h5>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/scheduled_doses/index.html.erb
<% if @patient.missed_scheduled_dose? %>
    <div class="alert alert-dismissible alert-warning">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Warning!</h4>
      <p>Looks like you missed a scheduled dose yesterday. Please contact <a href="<%= patient_conversations_path(@patient) %>" class="alert-link">your physician</a>.</p>
    </div>
<% end %>

<h1>List of Scheduled Doses for <%= @patient.name %> Today:</h1>

<div class="scheduled_doses">
  <% @patient.scheduled_doses_for_today.each do |sd| %>
    <%= render partial: "scheduled_dose", locals: {:sd => sd} %>
  <% end %>
</div>






    

app/views/scheduled_doses/update.js.erb
var sd = new ScheduledDose(<%= @scheduled_dose.id %>);
sd.update("<%= j render partial: "scheduled_dose", locals: {sd: @scheduled_dose} %>");